### ISSUE TITLE
"Sort by" location always shows the default one.

### ISSUE THREAD

**Issue by YuhanChen8789** [gcivil-nyu-org/spring2021-cs-gy-9223-class#100]
"Sort by" location always shows the default one. 

## Expected Behavior
After logging in, the "sort by" location should be the user's location stored in the database.
Each time user changes their address, the website should be able to update the location info.

## Current Behavior
Always show the default one: “Central Park North, New York, NY, USA"

**Comment by xiaodan-tang** [comment]
I guess the reason could be that you did not log in. If you are an anonymous user, the database will not store your address so every time you use the sort by distance feature, it will show the default location unless you change/update the location by entering your address and clicking on the "FIND" button.

After logging in, it will retrieve your location from the database and sort by your address.

We tested this feature on the production instance multiple times and it works well for us. Let us know if you still have the same issue.
