### ISSUE TITLE
"MOPD Compliant” and “COVID-19 Compliant" joint filter didn't show the right result

### ISSUE THREAD

**Issue by YuhanChen8789** [gcivil-nyu-org/spring2021-cs-gy-9223-class#101]
Click both "MOPD Compliant” and “COVID-19 Compliant" filter will show a restaurant MOPD but not COVID compliant

## Expected Behavior
After the user checking both the “MOPD Compliant” and “COVID-19 Compliant”, it will show restaurants that are both MOPD and COVID Compliant.

## Current Behavior
We only have one record here with restaurant MOPD compliant but not COVID compliant.

**Comment by xiaodan-tang** [comment]
The Covid compliant status attribute is inaccurate. Wrote a script to update it by getting the latest inspection records.
