### ISSUE TITLE
User browsing history "Delete" lable is misleading

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/spring2021-cs-gy-9223-class#131]
When looking at browsing history there is a large red "Delete" button, I think the "Delete" is confusing here , the user could think that we are deleting the restaurant. I would change the label to say "remove from history" or something like that

**Comment by parthmerchant** [comment]
This issue was corrected in #133 
- Replaced Delete button with X icon 
- Added on hover tooltip to show "Remove from History" 
- All functionality is intact for deleting a restaurant from browsing history as well as for pagination
