### ISSUE TITLE
Allow Builds on all branches

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2021-cs-gy-9223-class#16]
@HahnNYU I think we should set CI to run on more than only `main` branch. Could we set (revert) it to allow any branch?

https://github.com/gcivil-nyu-org/spring2021-cs-gy-9223-class/blob/0f3a74118050eccd45ca82780525f5ad5013cd9f/.travis.yml#L6-L8

**Comment by jackxujh** [comment]
It would be helpful to set up branch-specific travis builds.

**Comment by HahnNYU** [comment]
branch restriction was removed from .travis.yml file
