### ISSUE TITLE
Remove GitHub Actions setup

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/spring2021-cs-gy-9223-class#21]
## Expected Behavior
Only one CI provider per class repo

## Current Behavior
Both Travis and GitHub actions are present see https://github.com/gcivil-nyu-org/spring2021-cs-gy-9223-class/tree/main/.github/workflows

## Ideas for Improvement
remove GitHub actions

**Comment by HahnNYU** [comment]
GitHub Actions CI checks were removed
