### ISSUE TITLE
Travis token for coveralls

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2021-cs-gy-9223-class#31]
https://github.com/gcivil-nyu-org/spring2021-cs-gy-9223-class/blob/7ab322b24ec9f392487c8068a5ca5db0ba8d0bef/.coveralls.yml#L2

I would think we only need this token if the repo is not public. Could we double check?

**Comment by parthmerchant** [comment]
Double checked with the coveralls documentation. We do not need the repo-token for the public repository. Modified the .coveralls.yml file in this patch.
