### ISSUE TITLE
Could not see coverage information for class repo

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2021-cs-gy-9223-class#32]
The coverage page for class repo is: https://coveralls.io/github/gcivil-nyu-org/spring2021-cs-gy-9223-class

## Expected Behavior
There should be up-to-date test coverage for these three branches, and each has a coverage of **90% or higher**: 
- `main`
- `team-1`
- `team-2`

## Current Behavior
The link, when visited, shows old test coverage and info.

## Ideas for Improvement
Check the set up of coverage for class repo. And consider add badges on README.

**Comment by DarkBruce** [comment]
The badges to Travis and Coveralls is updated in README.md and cover the main, team-1 and team-2 branch with correct links.
