### ISSUE TITLE
Badges on class repo README do not point to correct website

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2021-cs-gy-9223-class#33]
## Expected Behavior
A badge for class repo build status and coverage stats, respectively, are expected near the beginning of README.  When you click on them, you can see the information about the class repo.

## Current Behavior
The badges link to the stats for team's repo.

## Ideas for Improvement
Update links beneath badges.

**Comment by parthmerchant** [comment]
Updated the badges for the class main repo in the README as well as coverages for the Travis and Coverall for both the Team 1 and Team 2 repo.
