### ISSUE TITLE
Daily build is not set up

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2021-cs-gy-9223-class#34]
## Expected Behavior
CI should build `main` daily, whether or not there is a pull request on it for that day.

## Current Behavior
The cron job is not set up.

## Ideas for Improvement
Set up a cron job on Travis CI to build `main` daily.

**Comment by DarkBruce** [comment]
A Cron job is added on Travis to automatically build the main branch on a daily manner with **Always run** option (daily build will always be triggered even if there has been a build within the last 24 hours).
