### ISSUE TITLE
User review appears under "Internal Review"

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/spring2021-cs-gy-9223-class#61]
Login to the site and leave a review under this restaurant 
http://dineline-production.herokuapp.com/restaurant/profile/4695/

## Expected Behavior
I would expect to see my review in the list of other reviews

## Current Behavior
![Screen Shot 2021-03-24 at 6 22 56 PM](https://user-images.githubusercontent.com/53953892/112391253-003bc200-8cce-11eb-8df3-121ecf33d283.png)

My review shows under "Internal Reviews" , not sure what this means

**Comment by YuhanChen8789** [comment]
Now it will shows as "Dineline reviews".
