### ISSUE TITLE
Can not update email on user profile

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/spring2021-cs-gy-9223-class#92]
## Expected Behavior
I would think that the user can change their email

## Current Behavior
Email fields is grayed out

## Steps to Reproduce
1. Login
2. Click on the Hi Username button to view a drop down list of buttons, and one of these buttons is User Profile;
3. Click on the User Profile button, which takes users to their profile page;
4. Edit their profile information by clicking on the Edit Profile button under the username shown in the profile page;
<img width="597" alt="Screen Shot 2021-04-07 at 7 03 25 PM" src="https://user-images.githubusercontent.com/53953892/113945256-fa68d500-97d3-11eb-8e1f-ab7f2945d263.png">

**Comment by xiaodan-tang** [comment]
Add user secondary email feature which allows the user to add/activate other emails. The user can also delete the primary email and secondary emails. After deleting the primary email, one of the other emails will automatically become the primary email.
