### ISSUE TITLE
Unable to edit review 

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/spring2021-cs-gy-9223-class#94]
I created a review with one picture in it
Later on I attempted to edit it and add another picture.
The review was not saved. 
See attached screen movie

## Expected Behavior
Expected existing review updated with new picture
## Current Behavior
I am guessing that the upload buttons are not properly connected to a model so they dont know that there is already a picture in this review, anyway, currently just does not work

https://user-images.githubusercontent.com/53953892/113946434-7401c280-97d6-11eb-92cf-804e995aabbc.mov

**Comment by ahmed1** [comment]
Duplicate issue as #93
