### ISSUE TITLE
third part redirect to google gives 400 error on dineline.herokuapp.com

### ISSUE THREAD

**Issue by HahnNYU** [gcivil-nyu-org/spring2021-cs-gy-9223-class#96]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
Should redirect to google login

## Current Behavior
third part redirect to google gives 400 error on dineline.herokuapp.com

## Steps to Reproduce

1. navigate to login 
2. click "Sign in with google"
![image](https://user-images.githubusercontent.com/67600408/113947161-ffc81e80-97d7-11eb-8afb-d2098e3ce4c4.png)

**Comment by ahmed1** [comment]
Duplicate Issue with #97
